// Real browser + disposable admin API state; no production users or settings are modified.
// CG_BROWSER_MODULE=/absolute/path/to/playwright/index.mjs node --test test/ai-testing-picker-browser.test.js
import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";
import express from "express";
import { ensureTestEnv } from "./helpers.js";
ensureTestEnv();

test("testing user search selects, removes and persists with keyboard and pointer at desktop and mobile widths", { skip: !process.env.CG_BROWSER_MODULE }, async (t) => {
  const { chromium } = await import(process.env.CG_BROWSER_MODULE);
  const { createAdminRouter } = await import("../src/web/routes/admin.js");
  const { setUser } = await import("../src/config/store.js");
  const { saveSettings, getAiTestingUsers } = await import("../src/config/settings.js");
  await setUser("UTESTALPHA", { name: "Alpha Tester", email: "alpha@example.test", approved: true });
  await setUser("UTESTBETA", { name: "Beta Tester", email: "beta@example.test", approved: true });
  for (let i = 0; i < 40; i++) await setUser(`UTEST${i}`, { name: `Sample User ${i}`, approved: true });
  saveSettings({ aiTestingUsers: ["USAVEDMISSING"] });
  const app = express();
  app.use(express.json());
  app.get("/api/skills", (_req, res) => res.json({ skills: [] }));
  app.get("/api/mcp/available", (_req, res) => res.json({ servers: [] }));
  app.get("/api/health", (_req, res) => res.json({ slack: { connected: false, status: "off" }, engines: {} }));
  app.use("/api", createAdminRouter({ slack: { snapshot: () => ({ status: "disconnected", connected: false }) } }));
  const publicDir = fileURLToPath(new URL("../public", import.meta.url));
  app.use(express.static(publicDir, { dotfiles: "allow" }));
  app.get("/settings", (_req, res) => res.sendFile(path.join(publicDir, "index.html"), { dotfiles: "allow" }));
  const server = await new Promise((resolve) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); });
  t.after(() => new Promise((resolve) => { server.closeAllConnections(); server.close(resolve); }));
  const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/settings`);
  const picker = page.locator("#set-ai-testing-users");
  const search = picker.getByRole("combobox");
  const save = page.locator("#save-settings");
  await search.waitFor();
  await picker.getByRole("button", { name: "Remove USAVEDMISSING" }).waitFor();
  assert.equal(await picker.getByRole("listbox").isVisible(), false, "directory starts collapsed");
  await search.fill("ALPHA");
  assert.equal(await picker.getByRole("option").count(), 1);
  assert.equal(await page.locator("#settings-dirty-msg").textContent(), "All changes saved", "search alone is not a settings edit");
  await search.press("ArrowDown");
  await search.press("Enter");
  await picker.getByRole("button", { name: "Remove Alpha Tester" }).waitFor();
  await search.fill("UTESTBETA");
  await picker.getByRole("option", { name: /Beta Tester/ }).click();
  await picker.getByRole("button", { name: "Remove Beta Tester" }).waitFor();
  await search.fill("Alpha");
  assert.equal(await picker.getByRole("option").count(), 0, "selected user cannot be added twice");
  assert.equal(await picker.getByRole("status").textContent(), "No matching users.");
  await search.press("Escape");
  const persist = async () => {
    const response = page.waitForResponse((r) => r.url().endsWith("/api/settings") && r.request().method() === "PUT");
    await save.click();
    assert.equal((await response).status(), 200);
    await page.waitForFunction(() => globalThis.document.querySelector("#settings-dirty-msg")?.textContent === "All changes saved");
  };
  await persist();
  assert.deepEqual(getAiTestingUsers(), ["USAVEDMISSING", "UTESTALPHA", "UTESTBETA"]);
  await page.reload();
  await picker.getByRole("button", { name: "Remove Alpha Tester" }).waitFor();
  await picker.getByRole("button", { name: "Remove USAVEDMISSING" }).click();
  await search.fill("");
  assert.equal(await picker.getByRole("option").count(), 30, "large directory is bounded");
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    await search.fill("sample");
    const box = await picker.boundingBox();
    assert.ok(box.x >= 0 && box.x + box.width <= width, "picker fits within the viewport");
    const list = await picker.getByRole("listbox").boundingBox();
    assert.ok(list.height <= 242, "results scroll within a compact box");
    assert.equal(await picker.evaluate((el) => el.scrollWidth <= el.clientWidth), true, "picker has no horizontal overflow");
    if (process.env.CG_UI_SCREENSHOTS) await picker.screenshot({ path: path.join(process.env.CG_UI_SCREENSHOTS, `ai-testing-picker-${width}.png`) });
  }
  await search.press("Escape");
  await picker.getByRole("button", { name: "Remove Alpha Tester" }).click();
  await picker.getByRole("button", { name: "Remove Beta Tester" }).click();
  await search.press("Escape");
  await persist();
  assert.deepEqual(getAiTestingUsers(), []);
  await page.reload();
  await search.waitFor();
  assert.equal(await picker.locator(".user-picker-chip").count(), 0);
  assert.deepEqual(errors, []);
});
