// Real settings UI against a disposable gateway store. No production settings change.
import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ensureTestEnv } from "./helpers.js";
ensureTestEnv();

test("settings creates, repoints and removes model shortcuts through the live catalog", { skip: !process.env.CG_BROWSER_MODULE }, async (t) => {
  const { chromium } = await import(process.env.CG_BROWSER_MODULE);
  const { createAdminRouter } = await import("../src/web/routes/admin.js");
  const { getModelShortcuts } = await import("../src/config/settings.js");
  const app = express();
  app.use(express.json());
  app.get("/api/skills", (_req, res) => res.json({ skills: [] }));
  app.get("/api/mcp/available", (_req, res) => res.json({ servers: [] }));
  app.get("/api/health", (_req, res) => res.json({ slack: { connected: false, status: "off" }, engines: {} }));
  app.use("/api", createAdminRouter({ slack: { snapshot: () => ({ connected: false, status: "disconnected" }) } }));
  const publicDir = fileURLToPath(new URL("../public", import.meta.url));
  app.use(express.static(publicDir, { dotfiles: "allow" }));
  app.get("/settings", (_req, res) => res.sendFile(path.join(publicDir, "index.html"), { dotfiles: "allow" }));
  const server = await new Promise((resolve) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); });
  t.after(() => new Promise((resolve) => { server.closeAllConnections(); server.close(resolve); }));
  const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/settings`);
  await page.waitForFunction(() => globalThis.document.querySelector("#add-model-shortcut")?.disabled === false);
  const persist = async () => {
    const response = page.waitForResponse((r) => r.url().endsWith("/api/settings") && r.request().method() === "PUT");
    await page.locator("#save-settings").click();
    assert.equal((await response).status(), 200);
    await page.waitForFunction(() => globalThis.document.querySelector("#settings-dirty-msg")?.textContent === "All changes saved");
  };
  await page.locator("#add-model-shortcut").click();
  const row = page.locator(".model-shortcut-row").first();
  await row.locator(".shortcut-name").fill("astra");
  await row.locator(".shortcut-engine").selectOption("codex");
  const modelIds = await row.locator(".shortcut-model option").evaluateAll((options) => options.map((option) => option.value));
  assert.ok(modelIds.length > 1, "the actual engine catalog supplies choices");
  await row.locator(".shortcut-model").selectOption(modelIds[0]);
  await persist();
  assert.deepEqual(getModelShortcuts().astra, { engine: "codex", model: modelIds[0] });
  await page.reload();
  await row.locator(".shortcut-model").waitFor();
  assert.equal(await row.locator(".shortcut-name").inputValue(), "astra");
  assert.equal(await row.locator(".shortcut-model").inputValue(), modelIds[0]);
  await row.locator(".shortcut-model").selectOption(modelIds[1]);
  await persist();
  assert.equal(getModelShortcuts().astra.model, modelIds[1]);
  await row.locator(".shortcut-engine").selectOption("claude");
  const claudeModel = await row.locator(".shortcut-model").inputValue();
  await persist();
  assert.deepEqual(getModelShortcuts().astra, { engine: "claude", model: claudeModel });
  await row.locator(".shortcut-remove").click();
  await persist();
  assert.deepEqual(getModelShortcuts(), {});
  assert.deepEqual(errors, [], "the settings page has no JavaScript errors");
});
