// Disposable real API + browser state. Set CG_BROWSER_MODULE to the installed Playwright module.
import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";
import express from "express";
import { ensureTestEnv } from "./helpers.js";
ensureTestEnv();

test("platform activation lists save independently and repaint after reload", { skip: !process.env.CG_BROWSER_MODULE }, async (t) => {
  const { chromium } = await import(process.env.CG_BROWSER_MODULE);
  const { createAdminRouter } = await import("../src/web/routes/admin.js");
  const settings = await import("../src/config/settings.js");
  const app = express();
  app.use(express.json());
  app.get("/api/skills", (_req, res) => res.json({ skills: [] }));
  app.get("/api/mcp/available", (_req, res) => res.json({ servers: [] }));
  app.get("/api/health", (_req, res) => res.json({ slack: { connected: false, status: "off" }, engines: {} }));
  app.use("/api", createAdminRouter({ slack: { snapshot: () => ({ status: "disconnected", connected: false }) } }));
  const publicDir = fileURLToPath(new URL("../public", import.meta.url));
  app.use(express.static(publicDir, { dotfiles: "allow" }));
  app.get("/settings", (_req, res) => res.sendFile(path.join(publicDir, "index.html"), { dotfiles: "allow" }));
  const server = await new Promise((resolve) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); });
  t.after(() => new Promise((resolve) => { server.closeAllConnections(); server.close(resolve); }));
  const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1366, height: 1000 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/settings`);
  const slack = page.locator("#set-mention-reactions");
  const teams = page.locator("#set-teams-mention-reactions");
  const google = page.locator("#set-google-chat-mention-reactions");
  await page.waitForFunction(() => globalThis.document.querySelector("#set-mention-reactions")?.value === "robot_face");
  assert.equal(await teams.inputValue(), "hearteyesrobot, alien, like, smilerobot");
  assert.equal(await google.inputValue(), "🤖");
  const card = teams.locator("xpath=../..");
  assert.match(await card.textContent(), /does not receive reaction events/);
  await slack.fill("rocket");
  await teams.fill(":ALIEN:");
  await google.fill("🚀");
  const persist = async () => {
    const response = page.waitForResponse((r) => r.url().endsWith("/api/settings") && r.request().method() === "PUT");
    await page.locator("#save-settings").click();
    const result = await response;
    assert.equal(result.status(), 200);
    await page.waitForFunction(() => globalThis.document.querySelector("#settings-dirty-msg")?.textContent === "All changes saved");
    return result.request().postDataJSON();
  };
  const first = await persist();
  assert.equal(first.mentionReactions, "rocket");
  assert.equal(first.teamsMentionReactions, ":ALIEN:");
  assert.equal(first.googleChatMentionReactions, "🚀");
  assert.equal(await teams.inputValue(), "alien", "successful response normalizes and repaints");
  await page.reload();
  await page.waitForFunction(() => globalThis.document.querySelector("#set-teams-mention-reactions")?.value === "alien");
  assert.equal(await slack.inputValue(), "rocket");
  assert.equal(await google.inputValue(), "🚀");
  await teams.fill("👍");
  const second = await persist();
  assert.equal(second.teamsMentionReactions, "👍");
  assert.equal(Object.hasOwn(second, "mentionReactions"), false);
  assert.equal(Object.hasOwn(second, "googleChatMentionReactions"), false);
  assert.deepEqual(settings.getMentionReactions("slack"), ["rocket"]);
  assert.deepEqual(settings.getMentionReactions("msteams"), ["👍"]);
  assert.deepEqual(settings.getMentionReactions("googlechat"), ["🚀"]);
  await page.setViewportSize({ width: 390, height: 844 });
  await teams.scrollIntoViewIfNeeded();
  assert.equal(await teams.isVisible(), true);
  assert.equal(await google.isVisible(), true);
  assert.deepEqual(errors, []);
});
