import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ensureTestEnv } from "./helpers.js";
ensureTestEnv();

test("automation UI saves reporting controls and exposes silent run logs after deletion", { skip: !process.env.CG_BROWSER_MODULE }, async (t) => {
  const { chromium } = await import(process.env.CG_BROWSER_MODULE);
  const { createAdminRouter } = await import("../src/web/routes/admin.js");
  const { addSchedule, getSchedules } = await import("../src/config/schedules.js");
  const { createScheduleRun, updateScheduleRun, appendScheduleRunEvent } = await import("../src/gateway/schedule-runs.js");
  const { upsertChannelEntry } = await import("../src/config/store.js");
  await upsertChannelEntry("CHEALTHBROWSER", { name: "automation-health-test", type: "channel" });
  const fixture = addSchedule({ channelId: "CHEALTHBROWSER", cron: "0 9 * * *", prompt: "Check email and report the outcome", description: "Inbox health", createdBy: "UTEST", notify: "none" });
  const run = createScheduleRun(fixture);
  updateScheduleRun(run.id, { status: "blocked", engineStatus: "completed", taskStatus: "blocked", deliveryStatus: "suppressed", summary: "Gmail connection expired", schedulingDelayMs: 1500, connections: [{ name: "Gmail", status: "unavailable" }] });
  appendScheduleRunEvent(run.id, { kind: "tool_use", name: "gmail.search" });
  const app = express();
  app.use(express.json());
  app.get("/api/skills", (_req, res) => res.json({ skills: [] }));
  app.get("/api/mcp/available", (_req, res) => res.json({ servers: [] }));
  app.get("/api/health", (_req, res) => res.json({ slack: { connected: false }, engines: {} }));
  app.use("/api", createAdminRouter({ slack: { snapshot: () => ({ status: "disconnected", connected: false }) } }));
  const publicDir = fileURLToPath(new URL("../public", import.meta.url));
  app.use(express.static(publicDir, { dotfiles: "allow" }));
  app.get("/automations", (_req, res) => res.sendFile(path.join(publicDir, "index.html"), { dotfiles: "allow" }));
  const server = await new Promise((resolve) => { const s = app.listen(0, "127.0.0.1", () => resolve(s)); });
  t.after(() => new Promise((resolve) => { server.closeAllConnections(); server.close(resolve); }));
  const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
  t.after(() => browser.close());
  const page = await browser.newPage();
  await page.goto(`http://127.0.0.1:${server.address().port}/automations`);
  await page.locator(".sched-open").click();
  await page.locator("#schedule-modal-visibility").selectOption("silent");
  await page.locator("#schedule-modal-result-policy").selectOption("on-result");
  await page.locator("#schedule-modal-delivery").selectOption("thread");
  await page.locator("#schedule-modal-thread").fill("1790355659.378439");
  await page.locator("#schedule-modal-failure-notify").uncheck();
  const saving = page.waitForResponse((r) => r.url().endsWith(`/api/schedules/${fixture.id}`) && r.request().method() === "PUT");
  await page.locator("#schedule-modal-save").click();
  assert.equal((await saving).status(), 200);
  const stored = getSchedules().find((s) => s.id === fixture.id);
  assert.deepEqual([stored.executionVisibility, stored.resultPolicy, stored.delivery, stored.deliveryThread, stored.failureNotify], ["silent", "on-result", "thread", "1790355659.378439", false]);
  await page.locator(".sched-history").click();
  await page.locator(".schedule-run-row").click();
  await page.locator("#schedule-history-detail h4").first().waitFor();
  const detail = await page.locator("#schedule-history-detail").innerText();
  assert.match(detail, /Blocked/);
  assert.match(detail, /Gmail connection expired/);
  assert.match(detail, /Unavailable/);
  assert.match(detail, /gmail.search/);
  assert.match(detail, /Run requested/i);
  assert.match(detail, /Last activity/i);
  assert.match(detail, /Scheduling delay[\s\S]*1.5s/i);
  assert.match(await page.locator("#schedule-history-summary").innerText(), /reported by the agent/);
  // The live history refreshes the selected run as well as the list, without user interaction.
  updateScheduleRun(run.id, { status: "running", engineStatus: "running", summary: "Polling observed this new activity", lastActivityAt: new Date().toISOString() });
  await page.getByText("Polling observed this new activity", { exact: true }).waitFor({ timeout: 10_000 });
  assert.match(await page.locator(".schedule-run-row").innerText(), /Running/);
  await page.keyboard.press("Escape");
  let closedRequests = 0;
  page.on("request", (request) => { if (/\/schedule-runs\/|\/schedules\/[^/]+\/runs/.test(request.url())) closedRequests++; });
  await page.waitForTimeout(5500);
  assert.equal(closedRequests, 0, "history polling stops when its dialog closes");
  await page.locator(".sched-del").click();
  await page.locator("#confirm-ok").click();
  await page.locator(".sched-row").waitFor({ state: "detached" });
  await page.locator("#schedule-history-all").click();
  await page.locator(".schedule-run-row").click();
  await page.locator("#schedule-history-detail h4").first().waitFor();
  assert.match(await page.locator("#schedule-history-detail").innerText(), /Inbox health/);
});
