// Practical, user-facing operating guide returned by the typed `/help` command. Keep this separate
// from app.js so its important workflows can be regression-tested without wiring a Slack app.
export const HELP_TEXT =
  "*How to use me*\n" +
  "In a DM, just send your request. In a channel, write `@agent your request`; keep follow-ups in the thread and @mention me again there. For typed commands in a channel, use forms such as `@agent /help`. The registered `/menu`, `/secrets`, `/model`, `/status`, and `/stop` Slack commands run at conversation top level without a mention.\n\n" +
  "• *Act on a message:* react with a configured activation emoji (default 🤖) to a new top-level message or a message in one of my threads. Administrators choose Slack’s own list in Settings → Agent defaults → Message activation reactions. In another bot's thread, @mention me instead.\n" +
  "• *Voice prompts:* attach a voice clip. In channels, @mention me or react 🤖 to start; DMs keep their normal behavior. When enabled and installed, audio is transcribed locally with Whisper large-v3-turbo; otherwise I use a completed Slack transcript. If none exists, click *Generate transcript* and trigger me again. Typed text stays as instructions, and raw audio is never sent to Claude or Codex.\n" +
  "• *Control a live run:* in a channel thread send `@agent stop` (a bare `stop` needs no mention only in a DM) or react 🛑 to stop just that run. `/stop` at top level stops every active run in this channel. If you send another message while I work, choose *Steer Conversation*, *Add to Queue*, or *Cancel Request*; the choice card disappears after a valid selection. `/next <message>` queues directly without asking.\n" +
  "• *Open files:* attach a file/image and ask me to read it, or use the 📂 button on a reply to browse this channel's folder, create new files/folders, and upload multiple files or a folder directly through the secured browser flow when configured—without storing the upload in Slack. With a Public URL, an opened file can be downloaded directly. In Worker/Auto mode, valid UTF-8 text files, including `.env`, JSON, configs, and scripts, can be edited regardless of extension; protected managed/credential/key paths stay read-only. You can also preview and share a file into the conversation, or say `send this file here` to have me attach a workspace file up to 25 MB directly in this thread. The Browse channel files message shortcut also keeps the selected thread.\n" +
  "• *Settings:* open ⚙️ Settings on a reply or from `/menu`. The tabs are General · Variables · MCPs · Skills · Automations · Resume. General manages channel defaults and this thread’s engine, model, and effort, plus Read-only, Worker, or Admin access. Auto approves tool requests; Lean omits optional skills and connectors. Allow network is a separate switch. A dedicated channel Codex login keeps the channel on Codex; an admin configures ChatGPT sign-in or an API key in the admin UI → Channel Runtime.\n" +
  "• *Add Composio:* In Personal mode, DM me `set my Composio token to …`, then delete the token message. In SDK mode, the admin key creates stable personal/channel identities automatically; you can manage your personal connections, while channel managers manage shared connections. Existing tokens remain saved when modes change. Use Settings → MCPs for connections and Cloud MCP selections. An admin can also add an HTTPS MCP URL and Bearer token in the admin UI → conversation Connections → Custom MCP servers, or Users → Personal MCP servers for one person’s runs. OAuth connections go through Composio. Say whose account to use when it matters.\n" +
  "• *Skills:* say `list skills` to browse the gateway's catalog, `add the <skill> skill for me` to carry one in your own runs, or (managers) `add the <skill> skill to this channel` / `apply the Development skills template`. Say `use the <skill name> skill` when you want one explicitly. Manage channel grants in Settings → Skills, or ask me to create or update a skill. New skills belong to this channel (personal in a DM) unless you request another scope; organization library changes follow admin governance. Unavailable grants produce a warning while available skills still load.\n" +
  "• *Questions and approvals:* answer clarification cards or use *Answer questions* for longer forms; choices are drafts until you submit. Permission cards show who may approve. Your submitted answer continues this thread.\n" +
  "• *Memory and rules:* say `remember that …` for a durable channel fact, or `always …` for a standing behavior rule. Memory is channel-scoped; never put secrets in it.\n" +
  "• *Gateway skills:* `gateway-usage` is installed automatically and teaches me chat tools, formatting, reminders, files, video understanding, and administration. `channel-memory` is automatic when channel memory is enabled—there is nothing to install.\n" +
  "• *Reminders and schedules:* ask naturally, for example `remind me in 2 hours to call the client` or `every Monday at 09:00 summarize new messages`. Reminders only post a nudge; scheduled tasks wake the agent to do work. Ask `list schedules` or `delete schedule <id>`, or open Settings → Automations to see next runs, pause or resume recurring schedules, cancel reminders, and stop loops. Checks can run every fixed number of days and DM you only on a matching result, then stop. For short repeated checks in this thread, ask a Claude Code engine to loop, for example `keep checking the deploy every 5 minutes until it finishes`; loops have a finite tick budget. React ✅ to acknowledge a tracked reminder.\n" +
  "• *Long-running work:* ask me to run it in the background. When this channel’s mode permits it, the gateway keeps the job alive after the current turn and reports back in this thread when it finishes. Container shell jobs start directly in Auto mode; host shell jobs require an admin’s exact-command approval.\n" +
  "• *SSH access:* when the host is configured for SSH, give me your `.pub` key, then say `enable SSH access for me` and `show my SSH connection instructions`. Users already allowed here can enable or revoke their own access without manager approval. Granting another person access needs a manager; containers with the operator home mounted cannot be opened through SSH.\n" +
  "• *Direct host work:* an organization admin can enable `/sudo` for one thread. Its admin messages run directly as the gateway daemon OS user, outside the channel container; non-admin messages to that thread are rejected. Use `/sudo off` to restore the normal container.\n" +
  "• *Useful checks:* `/status` shows active runs, background jobs, and schedules; `/pending` shows threads waiting on your decision; `/model` chooses an enabled engine (including opt-in Qwen providers), model, and effort; `@agent :shortcut task` picks a configured model for this thread; `/mode` shows the channel's tool-access mode.\n\n" +
  "*Commands* (this thread/channel)\n" +
  "• `/menu` — show only the Files, Variables, and Settings buttons; use `@agent /menu` inside a channel thread\n" +
  "• `/help` — show this guide\n" +
  "• `/clear` — start a fresh session in this thread\n" +
  "• `/fork [:model-shortcut] <new message>` — branch from a completed Claude or Codex container session into a linked new Slack thread; same-engine shortcuts fork the session, other-engine shortcuts start a new session with Slack history (after the current turn finishes)\n" +
  "• `/delete` — delete this thread's messages (admin; irreversible—everyone's if an admin user token is set in Settings, otherwise mine only)\n" +
  "• `/secrets` — open Variables for this channel, your personal scope, and (admins) the organization. Listings show names and masked values; add/replace follows your permissions. Channel values override personal values, then organization values. Hidden secrets work only on approved servers; a new server can require an admin approval. Passwords and connection strings stay usable by programs. Stored values are never shown in this console\n" +
  "• `/context` — token usage of the last turn\n" +
  "• `/resume` — terminal command to open this thread's session locally; `/resume <command or session id>` continues an existing session from this channel's folder in this thread\n" +
  "• `/pending` — threads where I'm waiting on your decision (alias `/followups`; bare `pending` / `my followups` work too)\n" +
  "• `/model` — choose channel/thread scope, an enabled engine, model, and effort (access policy is set in Settings)\n" +
  "• `/compact` — compact this thread's history on engines that support it (Claude Code, including Qwen; Codex → use `/clear`)\n" +
  "• `/mode [read|worker|admin]` — show or set this channel's base mode; `bash` is an alias for Worker. Managers may change Read-only/Worker; Admin requires an organization admin. Set Auto and Lean separately in Settings\n" +
  "• `/sudo [on|off|status]` — typed in-thread, organization-admin-only direct host execution; use `@agent /sudo` in channels; `/sudo` means on\n" +
  "• `/next <message>` — queue after the current run without showing the steer-or-queue choice\n" +
  "• `/status` — show active work and schedules in this conversation (top-level Slack command)\n" +
  "• `/stop` — stop every active run in this conversation (top-level; for one thread use `@agent stop`, `stop` in a DM, or 🛑)\n" +
  "• `/update` — update the gateway to the latest version and restart (admin)";
