import { spawn } from "node:child_process";
import { chmodSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createEditorLease } from "./editor-lease.js";
import { resolveContainerClaudeToken } from "../../gateway/claude-token-relay.js";
import { containerClaudeCredential } from "../../gateway/egress/grants.js";
import { CONTAINER_CLAUDE_CONFIG_DIR } from "./image-paths.js";

export const VSCODE_AUTH_DIR = "vscode";

// Claude Code's global state lives in $CLAUDE_CONFIG_DIR/.claude.json — the image sets
// CLAUDE_CONFIG_DIR, so ~/.claude.json is never read. Engine turns run headless (`claude -p`), which
// skips first-run onboarding, so a channel's file never records it; the first INTERACTIVE `claude` a
// developer starts over SSH or in VS Code then opens the theme picker and a login-method screen and
// looks signed out, although the relayed token works (a `-p` in the same shell answers). Record
// onboarding as done, and a theme only when none was chosen. Merge, never replace: this file is the
// channel's own Claude state. Unreadable JSON is left exactly as it is. Folder trust is deliberately
// NOT pre-accepted — that is the developer's decision, asked once per folder.
export const CLAUDE_ONBOARDING_FILE = `${CONTAINER_CLAUDE_CONFIG_DIR}/.claude.json`;
export const CLAUDE_ONBOARDING_SEED = `
const fs = require("node:fs");
const path = require("node:path");
const file = process.argv[1];
let config = {};
try { config = JSON.parse(fs.readFileSync(file, "utf8")); }
catch (error) { if (error.code !== "ENOENT") process.exit(0); }
if (!config || typeof config !== "object" || Array.isArray(config)) process.exit(0);
if (config.hasCompletedOnboarding === true && config.theme) process.exit(0);
config.hasCompletedOnboarding = true;
if (!config.theme) config.theme = "dark";
fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
const temporary = file + ".cg-" + process.pid;
fs.writeFileSync(temporary, JSON.stringify(config, null, 2), { mode: 0o600 });
fs.renameSync(temporary, file);
`;

export function vscodeAttachedContainerUri(container, workDir) {
  const authority = Buffer.from(String(container), "utf8").toString("hex");
  const pathname = String(workDir || "/home/agent").startsWith("/") ? String(workDir || "/home/agent") : `/${workDir}`;
  return `vscode-remote://attached-container+${authority}${encodeURI(pathname)}`;
}

function run(bin, args, { input = "", env = process.env, stdio = null } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, { env, stdio: stdio || (input ? ["pipe", "inherit", "inherit"] : "inherit") });
    child.on("error", reject);
    child.on("close", (code, signal) => code === 0 ? resolve() : reject(new Error(`${bin} ${args[0] || ""} ${signal ? `was killed by ${signal}` : `exited ${code}`}`)));
    if (input) child.stdin.end(input);
  });
}

// The `claude` an interactive session runs — ahead of the pinned CLI on the image PATH. Two
// shapes, decided at exec time by the session's own environment:
//  • an SSH session (CG_SSH_USER set by sshd from the developer's key line, and that developer's
//    prepared files present under `usersDir`): the developer's channel secrets are sourced, and
//    Claude starts exactly like a chat turn — the channel lockdown, the per-session MCP payload
//    and nothing else (gateway/ssh-session.js). The login is the access-only credentials file the
//    gateway wrote, so no token rides the environment and Claude shows the account itself.
//  • an editor attach or any other shell: the relayed login from the token file — the channel's
//    relay PLACEHOLDER when the egress proxy is the container's network (container-secrets P3),
//    so the file under the mounted artifact dir is worthless outside this container.
// Same file for both, so the two installers can never fight over it.
export function sshUsersDirOf(target) {
  return path.join(target.artifactDir, "ssh", "users");
}
export function renderClaudeWrapper({ tokenFile, usersDir = "" }) {
  const quote = (value) => `'${String(value).replaceAll("'", "'\\''")}'`;
  const sshBranch = usersDir ? [
    `d=${quote(usersDir)}/"\${CG_SSH_USER:-}"`,
    'if [ -n "${CG_SSH_USER:-}" ] && [ -r "$d/env" ] && [ -r "$d/mcp.json" ] && [ -r "$d/settings.json" ]; then',
    '  set -a; . "$d/env"; set +a',
    '  note=""; [ -r "$d/session.md" ] && note="$d/session.md"',
    '  exec /usr/local/bin/claude --setting-sources "" --settings "$d/settings.json" --mcp-config "$d/mcp.json" --strict-mcp-config ${note:+--append-system-prompt-file "$note"} "$@"',
    "fi",
  ] : [];
  return [
    "#!/bin/sh",
    "# Generated by ChannelGate — the claude an interactive session in this channel runs (docs/SSH-ACCESS.md).",
    `: "\${CLAUDE_CONFIG_DIR:=${CONTAINER_CLAUDE_CONFIG_DIR}}"`,
    "export CLAUDE_CONFIG_DIR",
    ...sshBranch,
    `if [ -z "\${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -r ${quote(tokenFile)} ]; then`,
    `  CLAUDE_CODE_OAUTH_TOKEN="$(cat ${quote(tokenFile)})"`,
    "  export CLAUDE_CODE_OAUTH_TOKEN",
    "fi",
    'exec /usr/local/bin/claude "$@"',
    "",
  ].join("\n");
}

// The `codex` an SSH session runs — Codex's twin of the claude wrapper (QA-0925: over SSH Codex had
// no gateway MCP, no Composio and none of the developer's secrets). In an SSH session whose files
// the gateway prepared, it sources the developer's secrets, adds the session's MCP servers as the
// same `-c mcp_servers.*` overrides a chat turn uses (codex-args.sh — credentials stay in the 0600
// bundle their helpers read, never argv), and — when started from HOME, `/` or a parent of the
// channel folder, where there is no project context — starts in the channel folder so its AGENTS.md
// applies; anywhere else it stays put, so relative paths and `codex resume` keep their meaning. Anything else falls straight through to the pinned CLI.
export const CONTAINER_CODEX_BIN = "/usr/local/bin/codex";
export function renderCodexWrapper({ usersDir, codexBin = CONTAINER_CODEX_BIN }) {
  const quote = (value) => `'${String(value).replaceAll("'", "'\\''")}'`;
  return [
    "#!/bin/sh",
    "# Generated by ChannelGate — the codex an SSH session in this channel runs (docs/SSH-ACCESS.md).",
    `d=${quote(usersDir)}/"\${CG_SSH_USER:-}"`,
    'if [ -n "${CG_SSH_USER:-}" ] && [ -r "$d/env" ] && [ -r "$d/codex-args.sh" ]; then',
    '  set -a; . "$d/env"; set +a',
    '  . "$d/codex-args.sh"',
    '  if [ -n "${CG_WORKDIR:-}" ] && [ -d "$CG_WORKDIR" ]; then',
    '    here=""; [ "$PWD" = "${HOME:-}" ] && here=1',
    '    case "$CG_WORKDIR/" in "${PWD%/}"/*) [ "$PWD" = "$CG_WORKDIR" ] || here=1 ;; esac',
    '    if [ -n "$here" ]; then cd "$CG_WORKDIR" && printf \'codex: starting in the channel folder %s\\n\' "$CG_WORKDIR" >&2; fi',
    "  fi",
    "fi",
    `exec ${quote(codexBin)} "$@"`,
    "",
  ].join("\n");
}
// `with-secrets <command…>` runs one command with the developer's channel secrets (the same file
// the wrappers source); bare, it says how to load them into the current shell.
export function renderWithSecrets({ usersDir }) {
  const quote = (value) => `'${String(value).replaceAll("'", "'\\''")}'`;
  return [
    "#!/bin/sh",
    "# Generated by ChannelGate — run a command with this SSH session's channel secrets.",
    `f=${quote(usersDir)}/"\${CG_SSH_USER:-}"/env`,
    'if [ -z "${CG_SSH_USER:-}" ] || [ ! -r "$f" ]; then echo "with-secrets: no prepared SSH session secrets here" >&2; exit 1; fi',
    'if [ "$#" -eq 0 ]; then printf \'Load them into this shell with:  set -a; . %s; set +a\\n\' "$f"; exit 0; fi',
    'set -a; . "$f"; set +a',
    'exec "$@"',
    "",
  ].join("\n");
}
export async function installSshCodexWrapper(target, cliBin, { runCommand = run, usersDir = sshUsersDirOf(target) } = {}) {
  for (const [name, body] of [["codex", renderCodexWrapper({ usersDir })], ["with-secrets", renderWithSecrets({ usersDir })]]) {
    await runCommand(cliBin, ["exec", "-i", target.container.name, "sh", "-c", `umask 077; mkdir -p /home/agent/.local/bin; cat > /home/agent/.local/bin/${name}; chmod 700 /home/agent/.local/bin/${name}`], { input: body });
  }
}

// The token file lives in the ARTIFACT dir, which the container mounts: every process in the box can
// read it. So it holds exactly what a turn's CLAUDE_CODE_OAUTH_TOKEN holds — the channel's relay
// placeholder (`containerClaudeCredential`) when the egress proxy is this container's network, the
// relayed access token only in the legacy bridge mode — and the returned `relay` is that same
// container-side form (the plan facts — expiry, scopes, subscription, tier — stay the real login's,
// they are not secrets). It is removed when the editor launcher exits and when a channel's last SSH
// session ends (gateway/ssh-session.js releaseSshSession).
export async function installVscodeClaudeRelay(target, cliBin, {
  resolveToken = resolveContainerClaudeToken,
  runCommand = run,
  usersDir = sshUsersDirOf(target),
  channelId = "",
} = {}) {
  const real = await resolveToken();
  if (!real.token) {
    if (real.source === "api-key") {
      throw new Error("Claude uses the daemon's API key, which is deliberately not exported to an interactive editor terminal. Sign in to Claude on the host or configure a claude setup-token for VS Code attach.");
    }
    throw new Error(real.error || "Claude has no login available for the editor container");
  }
  const relay = containerClaudeCredential({ target, relay: real, channelId: channelId || target?.meta?.channelId || "" });
  const dir = path.join(target.artifactDir, VSCODE_AUTH_DIR);
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const tokenFile = path.join(dir, "claude-token");
  writeFileSync(tokenFile, relay.token, { mode: 0o600 });
  chmodSync(tokenFile, 0o600);
  const wrapper = renderClaudeWrapper({ tokenFile, usersDir });
  await runCommand(cliBin, ["exec", "-i", target.container.name, "sh", "-c", "umask 077; mkdir -p /home/agent/.local/bin; cat > /home/agent/.local/bin/claude; chmod 700 /home/agent/.local/bin/claude"], { input: wrapper });
  // Best effort: without it the editor still works, it just greets the developer with onboarding.
  try { await runCommand(cliBin, ["exec", target.container.name, "node", "-e", CLAUDE_ONBOARDING_SEED, CLAUDE_ONBOARDING_FILE]); }
  catch { /* never block an attach on Claude's first-run flag */ }
  return { source: relay.source, expiresAt: relay.expiresAt, tokenFile, relay };
}

export function clearVscodeClaudeRelay(target) {
  rmSync(path.join(target.artifactDir, VSCODE_AUTH_DIR, "claude-token"), { force: true });
}

export async function launchVscodeContainer(target, {
  cliBin,
  codeBin = "code",
  runCommand = run,
  resolveToken,
  refreshMs = 20 * 60_000,
  log = console,
} = {}) {
  if (!cliBin) throw new Error("container CLI is unavailable");
  const lease = createEditorLease(target);
  let timer = null;
  let stopping = false;
  let refreshing = Promise.resolve();
  try {
    const auth = await installVscodeClaudeRelay(target, cliBin, { resolveToken, runCommand });
    const refresh = () => {
      refreshing = refreshing.then(async () => {
        if (stopping) return;
        try { await installVscodeClaudeRelay(target, cliBin, { resolveToken, runCommand }); }
        catch (error) { log.warn?.(`[vscode] Claude login refresh failed: ${error?.message || error}`); }
      });
    };
    timer = setInterval(refresh, refreshMs);
    timer.unref?.();
    const uri = vscodeAttachedContainerUri(target.container.name, target.workDir);
    await runCommand(codeBin, ["--wait", "--folder-uri", uri]);
    return { uri, auth };
  } finally {
    stopping = true;
    if (timer) clearInterval(timer);
    await refreshing;
    clearVscodeClaudeRelay(target);
    lease.release();
  }
}
