name: Public documentation

on:
  push:
    branches: [main, beta]
    paths:
      - 'documentation/**'
      - 'docs/**'
      - 'INSTALL.md'
      - 'CHANGELOG.md'
      - 'SUPPORT.md'
      - '.github/workflows/documentation.yml'
  pull_request:
    paths:
      - 'documentation/**'
      - 'docs/**'
      - 'INSTALL.md'
      - 'CHANGELOG.md'
      - 'SUPPORT.md'
      - '.github/workflows/documentation.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: documentation/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm audit --omit=dev --audit-level=high
